### ISSUE TITLE
Unable to run one node 10.1.0

### ISSUE THREAD

**Issue by RobinMglsk** [NEEOInc/neeo-sdk#75]
/usr/src/app/node_modules/neeo-sdk/lib/nodecheck.js:10
    throw new Error('You must run the NEEO SDK on node >= 6.0. Your current node version is ' + process.versions.node + '.');
    ^

Error: You must run the NEEO SDK on node >= 6.0. Your current node version is 10.1.0.
    at Object.module.exports.checkNodeVersion (/usr/src/app/node_modules/neeo-sdk/lib/nodecheck.js:10:11)
    at Object.<anonymous> (/usr/src/app/node_modules/neeo-sdk/lib/index.js:9:11)
    at Module._compile (internal/modules/cjs/loader.js:678:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:689:10)
    at Module.load (internal/modules/cjs/loader.js:589:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:528:12)
    at Function.Module._load (internal/modules/cjs/loader.js:520:3)
    at Module.require (internal/modules/cjs/loader.js:626:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/usr/src/app/node_modules/neeo-sdk/index.js:3:18)
    at Module._compile (internal/modules/cjs/loader.js:678:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:689:10)
    at Module.load (internal/modules/cjs/loader.js:589:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:528:12)
    at Function.Module._load (internal/modules/cjs/loader.js:520:3)
    at Module.require (internal/modules/cjs/loader.js:626:17)

**Comment by neophob** [comment]
thanks, this bug will be fixed in the next sdk release

**Comment by neophob** [comment]
updated SDK v0.50.3 fixes this, check out the next branch
